# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
        - prometheus:9090
 
  - job_name: grafana
    scrape_interval: 15s
    static_configs:
      - targets:
        - grafana:3000

  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: node-exporter
    scrape_interval: 15s
    static_configs:
      - targets:
        - node-exporter:9100
#JVM Monitoring
  - job_name: quarkus-jvm
    scrape_interval: 15s
    static_configs:
      - targets:
          - quarkus-jvm:8080
    metrics_path: /q/metrics

  - job_name: spring-jvm-simple
    scrape_interval: 15s
    static_configs:
      - targets:
          - spring-jvm-simple:8080
    metrics_path: /actuator/prometheus

  - job_name: micronaut-jvm
    scrape_interval: 15s
    static_configs:
      - targets:
          - micronaut-jvm:8080
    metrics_path: /prometheus

#native Monitoring
  - job_name: quarkus-native
    scrape_interval: 15s
    static_configs:
      - targets:
          - quarkus-native:8080
    metrics_path: /q/metrics

  - job_name: spring-native-simple
    scrape_interval: 15s
    static_configs:
      - targets:
          - spring-native-simple:8080
    metrics_path: /actuator/prometheus

  - job_name: micronaut-native
    scrape_interval: 15s
    static_configs:
      - targets:
          - micronaut-native:8080
    metrics_path: /prometheus
