---
- name: Deploy Monitoring Stack
  hosts: manager  # Adjust this to match your inventory
  become: true  # Use this if you need elevated privileges
  remote_user: debian
  tasks:
    - name: Ensure the monitoring stack directory exists on remote nodes
      file:
        path: /home/debian/monitoringstack
        state: directory

    - name: Copy monitoring stack files to remote nodes
      copy:
        src: ../monitoringstack/  # Use absolute path for clarity
        dest: /home/debian/monitoringstack
        owner: debian  # Change owner to debian
        group: debian  # Change group to debian
        mode: '0755'  # Adjust permissions as needed

    - name: Change to the monitoring stack directory and run docker-compose
      command: docker compose up -d
      args:
        chdir: /home/debian/monitoringstack/
      register: docker_compose_result
      ignore_errors: yes  # Ignore errors if the command fails

    - name: Show the output of the docker-compose command
      debug:
        var: docker_compose_result.stdout_lines
