---
- name: Install Podman and run NGINX container with autostart
  hosts: container-lxc-host
  become: true
  remote_user: debian
  tasks:

    - name: Install Podman
      apt:
        name: podman

    - name: Run NGINX container on port 8624
      command: podman run -d -p 8624:80 --name cloud-nginx docker.io/library/nginx

    - name: Generate systemd service for cloud-nginx container
      command: podman generate systemd --name cloud-nginx --new --files
      args:
        chdir: /etc/systemd/system

    - name: Copy generated systemd service to systemd directory
      copy:
        src: "/etc/systemd/system/container-cloud-nginx.service"
        dest: "/etc/systemd/system/container-cloud-nginx.service"
        remote_src: true
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start the cloud-nginx service
      systemd:
        name: container-cloud-nginx.service
        enabled: true
        state: started
