all:
  children:
    lxc-host:
      hosts:
        container-lxc-host:
          ansible_host: 86.119.31.182
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    manager:
      hosts:
        docker-mgr-01:
          ansible_host: 86.119.31.193
          private_ip: 10.0.4.175
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    workers:
      hosts:
        docker-wrk-01:
          ansible_host: 86.119.31.10
          private_ip: 10.0.5.93
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        docker-wrk-02:
          ansible_host: 86.119.30.91
          private_ip: 10.0.0.214
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
