all:
  children:
    lxc-host:
      hosts:
        container-lxc-host:
          ansible_host: 86.119.31.43
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Disable strict host key checking 
    manager:
      hosts:
        docker-mgr-01:
          ansible_host: 86.119.30.91
          private_ip: 10.0.2.59
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Disable strict host key checking
    workers:
      hosts:
        docker-wrk-01:
          ansible_host: 86.119.30.66
          private_ip: 10.0.0.18
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Disable strict host key checking
        docker-wrk-02:
          ansible_host: 86.119.31.182
          private_ip: 10.0.0.70
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Disable strict host key checking
