all:
  children:
    manager:
      hosts:
        docker-mgr-01:
          ansible_host: 86.119.31.193
          private_ip: 10.0.5.98
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Disable strict host key checking
    workers:
      hosts:
        docker-wrk-01:
          ansible_host: 86.119.30.159
          private_ip: 10.0.4.209
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Disable strict host key checking
        docker-wrk-02:
          ansible_host: 86.119.31.182
          private_ip: 10.0.0.200
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Disable strict host key checking
