all:
  children:
    k8s-main:
      hosts:
        k8smain01:
          ansible_host: 86.119.46.91
          private_ip: 10.0.7.211
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k8smain02:
          ansible_host: 86.119.44.76
          private_ip: 10.0.5.126
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k8sworker01:
          ansible_host: 86.119.45.155
          private_ip: 10.0.0.192
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k3s-nodes:
      hosts:
        k3snode01:
          ansible_host: 86.119.47.108
          private_ip: 10.0.7.105
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k3snode02:
          ansible_host: 86.119.44.111
          private_ip: 10.0.2.20
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
