all:
  children:
    k8s-main:
      hosts:
        k8smain01:
          ansible_host: 86.119.45.126
          private_ip: 10.0.4.5
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k8smain02:
          ansible_host: 86.119.45.230
          private_ip: 10.0.10.16
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k8sworker01:
          ansible_host: 86.119.47.233
          private_ip: 10.0.3.243
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k3s-nodes:
      hosts:
        k3snode01:
          ansible_host: 86.119.46.200
          private_ip: 10.0.5.225
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k3snode02:
          ansible_host: 86.119.44.91
          private_ip: 10.0.9.61
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
