all:
  children:
    k8s-main:
      hosts:
        k8smain01:
          ansible_host: 86.119.29.197
          private_ip: 10.0.0.190
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k8smain02:
          ansible_host: 86.119.31.193
          private_ip: 10.0.2.220
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k8sworker01:
          ansible_host: 86.119.31.10
          private_ip: 10.0.5.149
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k3s-nodes:
      hosts:
        k3snode01:
          ansible_host: 86.119.29.243
          private_ip: 10.0.2.39
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        k3snode02:
          ansible_host: 86.119.31.182
          private_ip: 10.0.1.202
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
