---
- name: Setup Kubernetes Master Node
  hosts: k8smain01
  become: yes
  remote_user: debian
  tasks:

    - name: Initialize Kubernetes with kubeadm
      ansible.builtin.command:
        cmd: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///run/containerd/containerd.sock
      register: kubeadm_init_output
      changed_when: "'Your Kubernetes control-plane has initialized successfully!' in kubeadm_init_output.stdout"

    - name: Capture kubeadm join command
      ansible.builtin.set_fact:
        join_command: "{{ kubeadm_init_output.stdout | regex_search('kubeadm join.*', '\\0') }}"
      when: "'Your Kubernetes control-plane has initialized successfully!' in kubeadm_init_output.stdout"

    - name: Save the kubeadm join command to a file
      ansible.builtin.copy:
        content: |
          {{ join_command | replace('\\', '\\\\') | replace('"', '\\"') }}
        dest: "/tmp/kubeadm_join_command.sh"
        mode: '0755'
      when: join_command is defined

    - name: Apply sysctl settings for Kubernetes CRI
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
      notify:
        - Reload sysctl

    - name: Configure iptables to allow port 6443 for Kubernetes API
      ansible.builtin.command:
        cmd: iptables -I KUBE-FIREWALL -p tcp --dport 6443 -j ACCEPT

    - name: Set iptables alternatives
      ansible.builtin.command:
        cmd: update-alternatives --config iptables
        creates: /etc/alternatives/iptables

    - name: Install Calico Tigera operator manifest
      ansible.builtin.command:
        cmd: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/tigera-operator.yaml
        creates: /etc/kubernetes/pki/ca.crt  # Check if Calico operator is already applied

    - name: Download Calico custom resources manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/custom-resources.yaml
        dest: /tmp/custom-resources.yaml

    - name: Apply Calico custom resources manifest
      ansible.builtin.command:
        cmd: kubectl create -f /tmp/custom-resources.yaml
        creates: /etc/kubernetes/pki/ca.crt  # Check if custom resources are applied

    - name: Create .kube directory
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy Kubernetes admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'
        remote_src: yes

    - name: Change ownership of Kubernetes config
      file:
        path: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'
  handlers:
    - name: Reload sysctl
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: yes
