---
- name: Install and Configure containerd
  hosts: k8smain*
  become: yes
  remote_user: debian
  tasks:

    - name: Ensure overlay and br_netfilter modules are loaded
      ansible.builtin.modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - overlay
        - br_netfilter

    - name: Create /etc/modules-load.d/containerd.conf and add required modules
      ansible.builtin.copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'

    - name: Ensure /etc/containerd directory exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd config.toml file
      ansible.builtin.shell: containerd config default
      register: containerd_config
      changed_when: False

    - name: Create containerd config.toml file
      ansible.builtin.copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_config.stdout }}"
        mode: '0644'

    - name: Update SystemdCgroup to true in containerd config.toml
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup\s*=\s*false'
        line: '\1SystemdCgroup = true'
        backrefs: yes
        state: present


    - name: Restart containerd service
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: yes
