all:
  children:
    CephNodes:
      hosts:
        monitor01:
          ansible_host: 86.119.31.44
          private_ip: 10.0.3.16
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        osd01:
          ansible_host: 86.119.31.182
          private_ip: 10.0.0.206
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        osd02:
          ansible_host: 86.119.30.59
          private_ip: 10.0.1.245
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        osd03:
          ansible_host: 86.119.31.147
          private_ip: 10.0.0.87
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
