services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/debian/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "2"        # Maximal 2 CPUs
          memory: "2g"     # Maximal 2 GB RAM
    cpuset: "0"          # Beschränkt Nginx auf Core 0

  quarkus-native:
    image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/quarkus_native:quarkus-native-image-simplified
    environment:
      - API_URL=http://nginx:80
      - FILE_IMPORTER_ENABLED=true
      - FILE_IMPORTER_LOCATION_TYPE=URI
      - FILE_IMPORTER_IMPORT_LOCATION=/import
      - FILE_IMPORTER_DONE_LOCATION=/done
      - FILE_IMPORTER_WILDCARD=.+\.([Pp][Dd][Ff])\s*$
      - FILE_IMPORTER_CONFIG_NAME=testURIImporterConfig
      - FILE_IMPORTER_BATCH_SIZE=2000
      - FILE_IMPORTER_INTERVAL_SEC=30
      - FILE_IMPORTER_SLEEP_BEFORE_IMPORT=2
      - FILE_IMPORTER_SLEEP_TIME=10
      - FILE_IMPORTER_THREAD_COUNT=8
      - API_USERNAME=FHNW_SERVICE_MANAGER
      - API_PASSWORD=FezNNtMuauSxHGocPSF7
    volumes:
      - /home/debian/tmp/quarkus-native/import:/import
      - /home/debian/tmp/quarkus-native/done:/done
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"
    cpuset: "1"



  spring-native-simple:
    image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/spring_native:spring-native-image-simplified
    volumes:
      - /home/debian/tmp/spring-native/import:/import
      - /home/debian/tmp/spring-native/done:/done
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"
    cpuset: "2"


  micronaut-native:
    image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/micronaut_native:micronaut-native-image
    volumes:
      - /home/debian/tmp/micronaut-native/import:/import
      - /home/debian/tmp/micronaut-native/done:/done
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"
    cpuset: "3"
